autodor_first_site_url: https://avtodor-tr.ru/account
autodor_login_button_xpath: /html/body/div[1]/div[2]/div/div/div[1]/div/form/div[4]/input
autodor_password: ***
autodor_password_xpath: /html/body/div[1]/div[2]/div/div/div[1]/div/form/div[2]/input
autodor_second_site_url: https://lk.avtodor-tr.ru/account/movement
autodor_sheet: "***"
autodor_username: ***
autodor_username_xpath: /html/body/div[1]/div[2]/div/div/div[1]/div/form/div[1]/input
chat_id: '***'
credentials_file: ./creds.json
file_1c: orders_table.xlsx
onec_sheet: "***"
platon_clik_to_serch_xpath: /html/body/div[3]/div/div/div[2]/div[2]/div/div/div/div[2]/div/div[1]/div/div[5]/button
platon_first_site_url: https://lk.platon.ru/sign_in?locale=ru
platon_login_button_xpath: /html/body/div[1]/div[3]/form/div/div/div[3]/button
platon_password: ***
platon_password_xpath: /html/body/div[1]/div[3]/form/div/div/div[1]/div[2]/input
platon_second_site_url: https://lk.platon.ru/accounts/49853
platon_sheet: "***"
platon_username: ***
platon_username_xpath: /html/body/div[1]/div[3]/form/div/div/div[1]/div[1]/input
spravochnik_napravleni: "***"
spravochnik_tc: "***"
spravochnik_topliva: "***"
spreadsheet_id: ***
telegram_bot_token: ***
token_wialon: ***
wialon_first_site_url: https://hosting.wialon.com/login.html
wialon_login_button_xpath: /html/body/div/div/div/div[2]/div[1]/form/input[13]
wialon_password: ***
wialon_password_xpath: /html/body/div/div/div/div[2]/div[1]/form/input[12]
wialon_sheet: "***"
wialon_username: ***
wialon_username_xpath: /html/body/div/div/div/div[2]/div[1]/form/input[11]
